
package interfaz;

import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {
    private boolean conect = false;
    private Consultas c;
    private final String url = "jdbc:postgresql://localhost:5432/PECL3";
    
    public Main() {
        initComponents();
        user_fija.setVisible(false);
        pass_fija.setVisible(false);
        panel.setVisible(false);
        url_fija.setText(url);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        url_l = new javax.swing.JLabel();
        user_l = new javax.swing.JLabel();
        pass_l = new javax.swing.JLabel();
        pass_fija = new javax.swing.JLabel();
        url_fija = new javax.swing.JLabel();
        user_fija = new javax.swing.JLabel();
        pass_edit = new javax.swing.JTextField();
        user_edit = new javax.swing.JTextField();
        conect_b = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        lista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CONEXION CON LA BDD PECL3");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        url_l.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        url_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        url_l.setText("URL");
        getContentPane().add(url_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        user_l.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        user_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_l.setText("USUARIO");
        getContentPane().add(user_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        pass_l.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        pass_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_l.setText("CONTRASEÑA");
        getContentPane().add(pass_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        pass_fija.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        pass_fija.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pass_fija.setText("jLabel5");
        getContentPane().add(pass_fija, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 580, -1));

        url_fija.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        url_fija.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        url_fija.setText("jLabel5");
        getContentPane().add(url_fija, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 580, -1));

        user_fija.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        user_fija.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        user_fija.setText("jLabel5");
        getContentPane().add(user_fija, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 580, -1));

        pass_edit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        pass_edit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(pass_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 580, -1));

        user_edit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        user_edit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(user_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 580, -1));

        conect_b.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        conect_b.setText("CONECTAR");
        conect_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conect_bActionPerformed(evt);
            }
        });
        getContentPane().add(conect_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 110, -1));

        lista.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lista.setMaximumRowCount(22);
        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Consulta 1", "Consulta 2", "Consulta 3", "Consulta 4", "Consulta 5", "Consulta 6", "Consulta 7", "Consulta 8", "Consulta 9", "Consulta 10", "Consulta 11", "Consulta 12", "Consulta 13", "Consulta 14", "Consulta 15", "Consulta 16", "Consulta 17", "Consulta 18", "Consulta 19", "Consulta 20", "Consulta 21" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 780, 410));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void conect_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conect_bActionPerformed
        try{
            if(conect){//desconectar
                c.desconectar();
                conect_b.setText("CONECTAR");
                conect = false;
                user_fija.setVisible(false);
                pass_fija.setVisible(false);
                user_edit.setVisible(true);
                pass_edit.setVisible(true);
                panel.setVisible(false);
            } else{//conectar
                c = new Consultas(url, user_edit.getText(), pass_edit.getText());
                conect_b.setText("DESCONECTAR");
                conect = true;
                user_fija.setVisible(true);
                pass_fija.setVisible(true);
                user_fija.setText(user_edit.getText());
                pass_fija.setText(pass_edit.getText());
                user_edit.setVisible(false);
                pass_edit.setVisible(false);
                panel.setVisible(true);
                lista.setSelectedIndex(0);
                consola.setText("");
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            String excep = ex.getMessage();
            if(excep.length()>120){
                String s1 = excep.substring(0, excep.length()/3);
                String s2 = excep.substring((excep.length()/3), (excep.length()/3)*2);
                String s3 = excep.substring(((excep.length()/3)*2));
                JOptionPane.showMessageDialog(this, s1+"\n"+s2+"\n"+s3, "WARNING", JOptionPane.WARNING_MESSAGE);
            } else JOptionPane.showMessageDialog(this, ex.getMessage(), "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_conect_bActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        try {
            int consulta = lista.getSelectedIndex();
            if(consulta>0) consola.setText(c.consultar(consulta));
        } catch (SQLException ex) {
            String excep = ex.getMessage();
            if(excep.length()>120){
                String s1 = excep.substring(0, excep.length()/3);
                String s2 = excep.substring((excep.length()/3), (excep.length()/3)*2);
                String s3 = excep.substring(((excep.length()/3)*2));
                JOptionPane.showMessageDialog(this, s1+"\n"+s2+"\n"+s3, "WARNING", JOptionPane.WARNING_MESSAGE);
            } else JOptionPane.showMessageDialog(this, ex.getMessage(), "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_listaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conect_b;
    private javax.swing.JTextArea consola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField pass_edit;
    private javax.swing.JLabel pass_fija;
    private javax.swing.JLabel pass_l;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel url_fija;
    private javax.swing.JLabel url_l;
    private javax.swing.JTextField user_edit;
    private javax.swing.JLabel user_fija;
    private javax.swing.JLabel user_l;
    // End of variables declaration//GEN-END:variables
}
